INSERT INTO BASE_CD (CD_TP, CD_V, CD_NM, CD_SORT, CD_USE)VALUES('DEPT_CD', '01', '총장실', 1, 'Y');
INSERT INTO BASE_CD (CD_TP, CD_V, CD_NM, CD_SORT, CD_USE)VALUES('DEPT_CD', '02', '비서실', 2, 'Y');
INSERT INTO BASE_CD (CD_TP, CD_V, CD_NM, CD_SORT, CD_USE)VALUES('DEPT_CD', '03', '교무과', 3, 'Y');